.\wcmp.exe .\testcases\input\input0.txt .\testcases\output_1\output0.txt .\testcases\output\output0.txt
.\wcmp.exe .\testcases\input\input1.txt .\testcases\output_1\output1.txt .\testcases\output\output1.txt
.\wcmp.exe .\testcases\input\input2.txt .\testcases\output_1\output2.txt .\testcases\output\output2.txt
.\wcmp.exe .\testcases\input\input3.txt .\testcases\output_1\output3.txt .\testcases\output\output3.txt
.\wcmp.exe .\testcases\input\input4.txt .\testcases\output_1\output4.txt .\testcases\output\output4.txt
.\wcmp.exe .\testcases\input\input5.txt .\testcases\output_1\output5.txt .\testcases\output\output5.txt
.\wcmp.exe .\testcases\input\input6.txt .\testcases\output_1\output6.txt .\testcases\output\output6.txt
.\wcmp.exe .\testcases\input\input7.txt .\testcases\output_1\output7.txt .\testcases\output\output7.txt
.\wcmp.exe .\testcases\input\input8.txt .\testcases\output_1\output8.txt .\testcases\output\output8.txt
.\wcmp.exe .\testcases\input\input9.txt .\testcases\output_1\output9.txt .\testcases\output\output9.txt
.\wcmp.exe .\testcases\input\input10.txt .\testcases\output_1\output10.txt .\testcases\output\output10.txt
.\wcmp.exe .\testcases\input\input11.txt .\testcases\output_1\output11.txt .\testcases\output\output11.txt
.\wcmp.exe .\testcases\input\input12.txt .\testcases\output_1\output12.txt .\testcases\output\output12.txt
.\wcmp.exe .\testcases\input\input13.txt .\testcases\output_1\output13.txt .\testcases\output\output13.txt
.\wcmp.exe .\testcases\input\input14.txt .\testcases\output_1\output14.txt .\testcases\output\output14.txt
