(type .\testcases\input\input0.txt | .\solution_0.exe) 1> .\testcases\output\output0.txt
(type .\testcases\input\input1.txt | .\solution_0.exe) 1> .\testcases\output\output1.txt
(type .\testcases\input\input2.txt | .\solution_0.exe) 1> .\testcases\output\output2.txt
(type .\testcases\input\input3.txt | .\solution_0.exe) 1> .\testcases\output\output3.txt
(type .\testcases\input\input4.txt | .\solution_0.exe) 1> .\testcases\output\output4.txt
(type .\testcases\input\input5.txt | .\solution_0.exe) 1> .\testcases\output\output5.txt
(type .\testcases\input\input6.txt | .\solution_0.exe) 1> .\testcases\output\output6.txt
(type .\testcases\input\input7.txt | .\solution_0.exe) 1> .\testcases\output\output7.txt
(type .\testcases\input\input8.txt | .\solution_0.exe) 1> .\testcases\output\output8.txt
(type .\testcases\input\input9.txt | .\solution_0.exe) 1> .\testcases\output\output9.txt
(type .\testcases\input\input10.txt | .\solution_0.exe) 1> .\testcases\output\output10.txt
(type .\testcases\input\input11.txt | .\solution_0.exe) 1> .\testcases\output\output11.txt
(type .\testcases\input\input12.txt | .\solution_0.exe) 1> .\testcases\output\output12.txt
(type .\testcases\input\input13.txt | .\solution_0.exe) 1> .\testcases\output\output13.txt
(type .\testcases\input\input14.txt | .\solution_0.exe) 1> .\testcases\output\output14.txt
